# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Betafit <- function(X, lam, y, V, p) {
    .Call('RRRR615_Betafit', PACKAGE = 'RRRR615', X, lam, y, V, p)
}

mulr <- function(X, y) {
    .Call('RRRR615_mulr', PACKAGE = 'RRRR615', X, y)
}

rcppeigen_hello_world <- function() {
    .Call('RRRR615_rcppeigen_hello_world', PACKAGE = 'RRRR615')
}

rcppeigen_outerproduct <- function(x) {
    .Call('RRRR615_rcppeigen_outerproduct', PACKAGE = 'RRRR615', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('RRRR615_rcppeigen_innerproduct', PACKAGE = 'RRRR615', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('RRRR615_rcppeigen_bothproducts', PACKAGE = 'RRRR615', x)
}

tr <- function(X, lam, y, V, p) {
    .Call('RRRR615_tr', PACKAGE = 'RRRR615', X, lam, y, V, p)
}

Yfit <- function(X, beta, Y, n) {
    .Call('RRRR615_Yfit', PACKAGE = 'RRRR615', X, beta, Y, n)
}

